[project]
name = "my-project"
version = "0.1.0"
description = "Progetto con dipendenze scientifiche e torch"
authors = [{ name = "Il Tuo Nome", email = "you@example.com" }]
requires-python = ">=3.8"

dependencies = [
    "numpy==1.21.0",
    "pandas==1.3.0",
    "scikit-learn==1.1.1",
    "scipy==1.6.0",
    "torch==1.8.1",
    "torch-geometric==1.7.2",
    "tqdm==4.61.2"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
